# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bf19f2fcc40b726500447ab53455e0869fbaed9f4cc6dda29473f5ae92ecb2118748e76062f1bbd2a73771b98e2c4b987bf022a0d26e0e2f260ab471bbce98c

test:
  secret_key_base: 68308e847d519e7a56176cdb1ff24df79df8bbe4e680fdbd4f67db17fdc523e6b926ddf5fe20b53e65d2db8d9998b0349b3328e875c01c43a08de55d466c8c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
